const birthInput = document.getElementById("birth-date");
const currentInput = document.getElementById("current-date");

const yearsEl = document.getElementById("years");
const monthsEl = document.getElementById("months");
const daysEl = document.getElementById("days");

const calculateBtn = document.getElementById("calculate-btn");
const resetBtn = document.getElementById("reset-btn");
const pdfBtn = document.getElementById("pdf-btn");
const themeBtn = document.getElementById("theme-toggle");

// auto date
window.addEventListener("DOMContentLoaded", () => {
    currentInput.value = new Date().toISOString().split("T")[0];
});

// calculate
calculateBtn.addEventListener("click", () => {

    if (!birthInput.value) {
        alert("Enter Date of Birth");
        return;
    }

    const birth = new Date(birthInput.value);
    const current = new Date(currentInput.value);

    let years = current.getFullYear() - birth.getFullYear();
    let months = current.getMonth() - birth.getMonth();
    let days = current.getDate() - birth.getDate();

    if (days < 0) {
        months--;
        days += new Date(current.getFullYear(), current.getMonth(), 0).getDate();
    }

    if (months < 0) {
        years--;
        months += 12;
    }

    yearsEl.innerText = years;
    monthsEl.innerText = months;
    daysEl.innerText = days;
});

// reset
resetBtn.addEventListener("click", () => {
    birthInput.value = "";
    currentInput.value = new Date().toISOString().split("T")[0];

    yearsEl.innerText = "00";
    monthsEl.innerText = "00";
    daysEl.innerText = "00";
});

// theme
themeBtn.addEventListener("click", () => {
    document.body.classList.toggle("light");
});

// PDF
pdfBtn.addEventListener("click", () => {

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const dob = birthInput.value;
    const currentDate = currentInput.value;

    const years = yearsEl.innerText;
    const months = monthsEl.innerText;
    const days = daysEl.innerText;

    if (!dob) {
        alert("Please calculate age first");
        return;
    }

    const birth = new Date(dob);

    const bornDay = birth.toLocaleDateString("en-US", {
        weekday: "long"
    });

    const totalDays = Math.floor(
        (new Date(currentDate) - birth) / (1000 * 60 * 60 * 24)
    );

    const totalWeeks = Math.floor(totalDays / 7);

    // TITLE
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("AGE REPORT", 65, 20);

    doc.line(20, 25, 190, 25);

    // INFO
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.text(`DOB: ${dob}`, 20, 45);
    doc.text(`Current Date: ${currentDate}`, 20, 55);

    doc.line(20, 65, 190, 65);

    // AGE
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("AGE DETAILS", 55, 82);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);

    doc.text(`${years} Years`, 20, 100);
    doc.text(`${months} Months`, 20, 110);
    doc.text(`${days} Days`, 20, 120);

    doc.text(`Total Days: ${totalDays}`, 20, 140);
    doc.text(`Total Weeks: ${totalWeeks}`, 20, 150);

    doc.text(`Born On: ${bornDay}`, 20, 165);

    doc.line(20, 185, 190, 185);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.text("Generated by Age Calculator App", 45, 200);

    doc.save("Age_Report.pdf");
});

window.addEventListener("load", () => {
    const loader = document.getElementById("loader");

    setTimeout(() => {
        loader.classList.add("hide");
    }, 1800); // 1.8 sec smooth experience
});